### ISSUE TITLE
CSS Modules css-loader issue

### ISSUE THREAD

**Issue by alejandronanez** [HenrikJoreteg/hjs-webpack#114]
Hi there guys, I don't want to spam here but I think this is the right place for my question.

By having this:

```css
/*test.css*/

.foo {
    color: red;
};

.bar {
    color: blue;
};
```

And importing it using `import styles from './test.css'`

```js

// webpack.config.js

config.module.loaders.push({
    test: /\.css$/,
      loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]'
});
```
I got this error on `npm start` -> `(webpack-dev-server)`
```shell

ERROR in ./~/css-loader!./~/postcss-loader!./~/style-loader!./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./src/containers/test.css
/Users/alejandro/Code/projects/redux-nav-exercise/node_modules/style-loader/index.js!/Users/alejandro/Code/projects/redux-nav-exercise/node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!/Users/alejandro/Code/projects/redux-nav-exercise/src/containers/test.css:1:4: Unknown word
// style-loader: Adds some css to the DOM by adding a <style> tag
   ^


ERROR in ./~/css-loader!./~/postcss-loader!./~/style-loader!./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./src/containers/test.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (/Users/alejandro/Code/projects/redux-nav-exercise/node_modules/css-loader/node_modules/postcss/lib/input.js:31:23)
    at parse (/Users/alejandro/Code/projects/redux-nav-exercise/node_modules/css-loader/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (/Users/alejandro/Code/projects/redux-nav-exercise/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Users/alejandro/Code/projects/redux-nav-exercise/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Users/alejandro/Code/projects/redux-nav-exercise/node_modules/css-loader/lib/processCss.js:171:11)
    at Object.module.exports (/Users/alejandro/Code/projects/redux-nav-exercise/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/containers/test.css 4:14-280 14:20-286
```

Am I missing something here? Am I editing wrong my loaders section of the `webpack.config.js` If this question is totally missplaced, please let me know and I close it.

**Comment by lukekarrys** [comment]
https://github.com/lukekarrys/repeatone.club/blob/master/webpack.config.es6#L110

Im not at my laptop right now but that's an example of how I've used css modules with this before. You have to replace the loader I think instead of just adding one.

**Comment by alejandronanez** [comment]
Fantastic @lukekarrys, thank you very much.

**Comment by tsterker** [comment]
The above link is broken, it is now: https://github.com/lukekarrys/repeatone.club/blob/master/webpack.config.js#L111

The important part for reference:
```js
const replaceLoader = (match, replacer) => (l) => {
  if (l && l.loader && l.loader.match(match)) {
    l.loader = l.loader.replace(match, replacer);
  }
};

// Happy, debuggable selectors in dev. Super compact selectors in prod.
const cssDevIdent = isDev ? '[path][name]___[local]___' : '';
const cssModulesLoader = `?modules&localIdentName=${cssDevIdent}[hash:base64:5]`;
const cssModuleMatch = /(^|!)(css-loader)($|!)/;
config.module.loaders.forEach(replaceLoader(cssModuleMatch, `$1$2${cssModulesLoader}$3`));
```
