### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by mtwallet** [HenrikJoreteg/hjs-webpack#212]
Hi, I have the following error when I run npm start:

```
webpack built 1a7fa0db84b6a2aa5b8c in 440ms
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 192.168.0.120:3000
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1233:19)
    at listen (net.js:1282:10)
    at net.js:1391:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

17 error Darwin 14.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.11.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error client@1.0.0 start: `hjs-dev-server`
22 error Exit status 1
23 error Failed at the client@1.0.0 start script 'hjs-dev-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the client package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     hjs-dev-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs client
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls client
23 error There is likely additional logging output above.
```

What am I doing wrong?

**Comment by fardormu** [comment]
The error appears to be stated here, `Error: listen EADDRNOTAVAIL 192.168.0.120:3000`.
A possible solution could be by specifying hostname and port in your `webpack.config.js`.
```
const config = require('hjs-webpack')({
  in: 'src/index.js',
  out: 'dist',
  clearBeforeBuild: true,
  devServer: {
    hostname: 'localhost', // or your loopback IP, normally 127.0.0.1
    port: 3000,
  },
})

module.exports = config
```
