### ISSUE TITLE
The webpack DedupePlugin seems to break `npm run build` for the prerendered html example

### ISSUE THREAD

**Issue by johnloy** [HenrikJoreteg/hjs-webpack#22]
More specifically, setting `NODE_ENV=production` before running `webpack` seems to cause this error. 

```bash
Error: No template for dependency: TemplateArgumentDependency
    at doDep (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/lib/NormalModule.js:116:23)
    at Array.forEach (native)
    at doBlock (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/lib/NormalModule.js:125:22)
    at DependenciesBlock.NormalModule.source (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/lib/NormalModule.js:159:2)
    at Tapable.ModuleTemplate.render (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/lib/ModuleTemplate.js:14:28)
    at Tapable.Template.renderChunkModules (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/lib/Template.js:80:31)
    at Tapable.<anonymous> (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/lib/MainTemplate.js:28:22)
    at Tapable.applyPlugins [as applyPluginsWaterfall] (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/node_modules/tapable/lib/Tapable.js:37:47)
    at Tapable.MainTemplate.render (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/lib/MainTemplate.js:111:20)
    at Tapable.createChunkAssets (/Users/johnloy/Code/hjs-webpack/examples/prerendered-html-files/node_modules/webpack/lib/Compilation.js:807:32)
```

Setting `NODE_ENV` to anything other than production seems to work fine.

Commenting this line seems to supress the problem, though I haven't dug into why:
https://github.com/HenrikJoreteg/hjs-webpack/blob/master/index.js#L116

**Comment by lukekarrys** [comment]
Thanks for the issue @johnloy! This turned out to be a doozy, and I'm not exactly sure why still but #22 fixed it. I'll try to get that merged and released sometime next week. If you need to get it working in the meantime, you should be able to copy the package.json from the PR and rerun `npm install` and it should then work.

**Comment by johnloy** [comment]
@lukekarrys No rush. I was just trying out the example. Thanks for the speedy response and fix!
