### ISSUE TITLE
Where to put entry.vendors

### ISSUE THREAD

**Issue by grbspltt** [HenrikJoreteg/hjs-webpack#52]
I went to your FluentConf where you had us use this module.  I'm struggling with this module (and all of webpack for that matter), I have vendor JS + CSS files that I want to put in entry.vendors

My config file: 

```javascript
module.exports = getConfig({
    //entry point
    in: 'src/app.jsx',
    out: 'public', //where compiled files will end up when finished
    isDev: process.env.NODE_ENV !== 'production',
    html: function(data){
        return { 'index.html': data.defaultTemplate() }; //default template
    },
    clearBeforeBuild: true,
    port:8080,
    entry:{
        vendors:[
            'jquery'
        ]
    },
    resolve:{
        alias:{
            jquery:'jquery/src/jquery.js'
        }
    },
    resolveLoader:{
        root: path.join( __dirname, 'node_modules')
    },
    plugins:[
        new webpack.ProvidePlugin({
            jQuery: 'jquery',
            $: 'jquery',
            'window.jQuery':'jquery'
        }),
        new webpack.optimize.CommonsChunkPlugin('vendors','vendors.js')
    ]
});
```

this error: 
```
node_modules\webpack\lib\NormalModuleFactory.js:70
                        var elements = request.replace(/^-?!+/, "").replace(/!!+/g, "!").split("!")
                                               ^
TypeError: undefined is not a function
    at Tapable.<anonymous> (C:\nodeProj\facebook\clientSide\node_modules\webpack\lib\NormalModuleFactory.js:70:27)
    at Tapable.<anonymous> (C:\nodeProj\facebook\clientSide\node_modules\webpack\lib\NormalModuleFactory.js:27:4)
    at Tapable.<anonymous> (C:\nodeProj\facebook\clientSide\node_modules\webpack\lib\NormalModuleFactory.js:154:3)
    at Tapable.applyPluginsAsyncWaterfall (C:\nodeProj\facebook\clientSide\node_modules\webpack\node_modules\tapable\lib\Tapable.js:75:69)
    at Tapable.NormalModuleFactory.create (C:\nodeProj\facebook\clientSide\node_modules\webpack\lib\NormalModuleFactory.js:139:7)
    at Tapable.<anonymous> (C:\nodeProj\facebook\clientSide\node_modules\webpack\lib\Compilation.js:211:11)
    at C:\nodeProj\facebook\clientSide\node_modules\webpack\node_modules\async\lib\async.js:182:20
    at C:\nodeProj\facebook\clientSide\node_modules\webpack\node_modules\async\lib\async.js:234:13
    at _arrayEach (C:\nodeProj\facebook\clientSide\node_modules\webpack\node_modules\async\lib\async.js:85:13)
    at _each (C:\nodeProj\facebook\clientSide\node_modules\webpack\node_modules\async\lib\async.js:76:13)

```
If I remove this snippet, it bundles, but does not accomplish what I'm trying to do.
```
entry:{
    vendors:['jquery']
}
```

**Comment by lukekarrys** [comment]
Hey @grbspltt!

So the `hjs-webpack` function doesn't merge all the keys that could appear on a webpack config. But what you can do is save the config to a variable and then manipulate it.

For example, if you wanted to add plugins to your webpack config you could do it like this:

```js
var config = getConfig(/*{...}*/);

// Add the plugins you want
// Same could be done for resolveLoader and resolve
config.plugins.push(
  new webpack.ProvidePlugin({
    jQuery: 'jquery',
    $: 'jquery',
    'window.jQuery':'jquery'
  }),
  new webpack.optimize.CommonsChunkPlugin('vendors','vendors.js')
)

module.exports = config
```

As for the `vendor`, since `hjs-webpack` has `entry` as an array but you're expecting it to be an object, it is a little different but the same type of thing as above can be done, where you manipulate the config. Something like this should work:

```js
config.entry = {
  vendors: ['jquery'],
  main: config.entry
};

module.exports = config;
```

Also note that since you are modifying the entry, you will need to use your own `html` so that you include both `vendors.js` and `app.js`. Here's a [fuller gist](https://gist.github.com/lukekarrys/8d6e47d8a8be3b7464bc) of what I ended up with when testing this out. Let me know if that works for you!

**Comment by lukekarrys** [comment]
I'm gonna close this (and document this type of thing better in #57). @grbspltt let me know if that isn't working for you.

**Comment by grbspltt** [comment]
@lukekarrys Your suggestion worked, thanks for the fix.
